[60.862302780] 2019-01-29 17:52:44,624 - INFO - launcher: Starting sanity checks
[61.861515045] 2019-01-29 17:52:44,625 - INFO - launcher: Checking for Python 3.5+
[63.072443008] 2019-01-29 17:52:44,626 - INFO - launcher: Checking console encoding
[63.906431198] 2019-01-29 17:52:44,627 - INFO - launcher: Setting console encoding to UTF-8
[63.906431198] 2019-01-29 17:52:44,627 - INFO - launcher: Ensuring we're in the right environment
[64.909458160] 2019-01-29 17:52:44,628 - INFO - launcher: Adding local bins/ folder to path
[1710.184097290] 2019-01-29 17:52:46,274 - INFO - launcher: Required checks passed.
[1714.180707932] 2019-01-29 17:52:46,278 - INFO - launcher: Optional checks passed.
[1714.180707932] 2019-01-29 17:52:46,278 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[2.5391521453857422] 2019-01-29 17:52:47,102 - WARNING - musicbot.config | In config.py::MainThread(7936), line 115 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[2.5401513576507568] 2019-01-29 17:52:47,103 - INFO - musicbot.config | In config.py::MainThread(7936), line 126 in run_checks: Using i18n: config/i18n/en.json
[2.5421500205993652] 2019-01-29 17:52:47,105 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 219 in _setup_logging: Set logging level to INFO
[2.5441496372222900] 2019-01-29 17:52:47,107 - DEBUG - musicbot.json | In json.py::MainThread(7936), line 8 in __init__: Init JSON obj with config/i18n/en.json
[2.8203082084655762] 2019-01-29 17:52:47,384 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 84 in __init__: Starting MusicBot 1.9.8_3
[2.8213090896606445] 2019-01-29 17:52:47,385 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 90 in __init__: Loaded autoplaylist with 2531 entries
[14.3504798412322998] 2019-01-29 17:52:58,914 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 915 in on_ready: Connection established, ready to go.
[14.3504798412322998] 2019-01-29 17:52:58,914 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 333 in _cache_app_info: Caching app info
[14.6348915100097656] 2019-01-29 17:52:59,198 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 737 in _scheck_ensure_env: Ensuring data folders exist
[14.6378912925720215] 2019-01-29 17:52:59,201 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 753 in _scheck_server_permissions: Checking server permissions
[14.6378912925720215] 2019-01-29 17:52:59,201 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 757 in _scheck_autoplaylist: Auditing autoplaylist
[14.6378912925720215] 2019-01-29 17:52:59,201 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 761 in _scheck_configs: Validating config
[14.6388864517211914] 2019-01-29 17:52:59,202 - DEBUG - musicbot.config | In config.py::MainThread(7936), line 216 in async_validate: Validating options...
[14.6388864517211914] 2019-01-29 17:52:59,202 - DEBUG - musicbot.bot | In bot.py::MainThread(7936), line 764 in _scheck_configs: Validating permissions config
[14.6388864517211914] 2019-01-29 17:52:59,202 - DEBUG - musicbot.permissions | In permissions.py::MainThread(7936), line 94 in async_validate: Validating permissions...
[14.6388864517211914] 2019-01-29 17:52:59,202 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 932 in on_ready: Connected: 539415268988944384/The CCs!#6228
[14.6408879756927490] 2019-01-29 17:52:59,204 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 940 in on_ready: Owner:     373811325387669516/999+STR#6157

[14.6418848037719727] 2019-01-29 17:52:59,205 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 943 in on_ready: Guild List:
[14.6428837776184082] 2019-01-29 17:52:59,206 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 947 in on_ready:  - The CCs
[14.6438839435577393] 2019-01-29 17:52:59,207 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 1003 in on_ready: Not bound to any text channels
[14.6448857784271240] 2019-01-29 17:52:59,208 - INFO - musicbot.bot | In bot.py::MainThread(7936), line 1029 in on_ready: Not autojoining any voice channels
